// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schedmessages.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	schedmessages.proto

It has these top-level messages:
	Quotum
	Organization
	ResourceVolume
	Decision
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Quotum struct {
	ProjectRatio float32 `protobuf:"fixed32,1,opt,name=ProjectRatio" json:"ProjectRatio,omitempty"`
	// Types that are valid to be assigned to Q:
	//	*Quotum_CpuHoursRatio
	//	*Quotum_GbRatio
	//	*Quotum_CpuHoursAbs
	//	*Quotum_GbAbs
	//	*Quotum_RamHoursAbs
	//	*Quotum_RamHoursRatio
	Q isQuotum_Q `protobuf_oneof:"Q"`
}

func (m *Quotum) Reset()                    { *m = Quotum{} }
func (m *Quotum) String() string            { return proto.CompactTextString(m) }
func (*Quotum) ProtoMessage()               {}
func (*Quotum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isQuotum_Q interface {
	isQuotum_Q()
}

type Quotum_CpuHoursRatio struct {
	CpuHoursRatio float32 `protobuf:"fixed32,10,opt,name=CpuHoursRatio,oneof"`
}
type Quotum_GbRatio struct {
	GbRatio float32 `protobuf:"fixed32,11,opt,name=GbRatio,oneof"`
}
type Quotum_CpuHoursAbs struct {
	CpuHoursAbs float32 `protobuf:"fixed32,12,opt,name=CpuHoursAbs,oneof"`
}
type Quotum_GbAbs struct {
	GbAbs float32 `protobuf:"fixed32,13,opt,name=GbAbs,oneof"`
}
type Quotum_RamHoursAbs struct {
	RamHoursAbs float32 `protobuf:"fixed32,14,opt,name=RamHoursAbs,oneof"`
}
type Quotum_RamHoursRatio struct {
	RamHoursRatio float32 `protobuf:"fixed32,15,opt,name=RamHoursRatio,oneof"`
}

func (*Quotum_CpuHoursRatio) isQuotum_Q() {}
func (*Quotum_GbRatio) isQuotum_Q()       {}
func (*Quotum_CpuHoursAbs) isQuotum_Q()   {}
func (*Quotum_GbAbs) isQuotum_Q()         {}
func (*Quotum_RamHoursAbs) isQuotum_Q()   {}
func (*Quotum_RamHoursRatio) isQuotum_Q() {}

func (m *Quotum) GetQ() isQuotum_Q {
	if m != nil {
		return m.Q
	}
	return nil
}

func (m *Quotum) GetProjectRatio() float32 {
	if m != nil {
		return m.ProjectRatio
	}
	return 0
}

func (m *Quotum) GetCpuHoursRatio() float32 {
	if x, ok := m.GetQ().(*Quotum_CpuHoursRatio); ok {
		return x.CpuHoursRatio
	}
	return 0
}

func (m *Quotum) GetGbRatio() float32 {
	if x, ok := m.GetQ().(*Quotum_GbRatio); ok {
		return x.GbRatio
	}
	return 0
}

func (m *Quotum) GetCpuHoursAbs() float32 {
	if x, ok := m.GetQ().(*Quotum_CpuHoursAbs); ok {
		return x.CpuHoursAbs
	}
	return 0
}

func (m *Quotum) GetGbAbs() float32 {
	if x, ok := m.GetQ().(*Quotum_GbAbs); ok {
		return x.GbAbs
	}
	return 0
}

func (m *Quotum) GetRamHoursAbs() float32 {
	if x, ok := m.GetQ().(*Quotum_RamHoursAbs); ok {
		return x.RamHoursAbs
	}
	return 0
}

func (m *Quotum) GetRamHoursRatio() float32 {
	if x, ok := m.GetQ().(*Quotum_RamHoursRatio); ok {
		return x.RamHoursRatio
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Quotum) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Quotum_OneofMarshaler, _Quotum_OneofUnmarshaler, _Quotum_OneofSizer, []interface{}{
		(*Quotum_CpuHoursRatio)(nil),
		(*Quotum_GbRatio)(nil),
		(*Quotum_CpuHoursAbs)(nil),
		(*Quotum_GbAbs)(nil),
		(*Quotum_RamHoursAbs)(nil),
		(*Quotum_RamHoursRatio)(nil),
	}
}

func _Quotum_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Quotum)
	// Q
	switch x := m.Q.(type) {
	case *Quotum_CpuHoursRatio:
		b.EncodeVarint(10<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.CpuHoursRatio)))
	case *Quotum_GbRatio:
		b.EncodeVarint(11<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.GbRatio)))
	case *Quotum_CpuHoursAbs:
		b.EncodeVarint(12<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.CpuHoursAbs)))
	case *Quotum_GbAbs:
		b.EncodeVarint(13<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.GbAbs)))
	case *Quotum_RamHoursAbs:
		b.EncodeVarint(14<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.RamHoursAbs)))
	case *Quotum_RamHoursRatio:
		b.EncodeVarint(15<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.RamHoursRatio)))
	case nil:
	default:
		return fmt.Errorf("Quotum.Q has unexpected type %T", x)
	}
	return nil
}

func _Quotum_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Quotum)
	switch tag {
	case 10: // Q.CpuHoursRatio
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_CpuHoursRatio{math.Float32frombits(uint32(x))}
		return true, err
	case 11: // Q.GbRatio
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_GbRatio{math.Float32frombits(uint32(x))}
		return true, err
	case 12: // Q.CpuHoursAbs
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_CpuHoursAbs{math.Float32frombits(uint32(x))}
		return true, err
	case 13: // Q.GbAbs
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_GbAbs{math.Float32frombits(uint32(x))}
		return true, err
	case 14: // Q.RamHoursAbs
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_RamHoursAbs{math.Float32frombits(uint32(x))}
		return true, err
	case 15: // Q.RamHoursRatio
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_RamHoursRatio{math.Float32frombits(uint32(x))}
		return true, err
	default:
		return false, nil
	}
}

func _Quotum_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Quotum)
	// Q
	switch x := m.Q.(type) {
	case *Quotum_CpuHoursRatio:
		n += proto.SizeVarint(10<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_GbRatio:
		n += proto.SizeVarint(11<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_CpuHoursAbs:
		n += proto.SizeVarint(12<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_GbAbs:
		n += proto.SizeVarint(13<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_RamHoursAbs:
		n += proto.SizeVarint(14<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_RamHoursRatio:
		n += proto.SizeVarint(15<<3 | proto.WireFixed32)
		n += 4
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Organization struct {
	Name  string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Quota *Quotum `protobuf:"bytes,2,opt,name=Quota" json:"Quota,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetQuota() *Quotum {
	if m != nil {
		return m.Quota
	}
	return nil
}

type ResourceVolume struct {
	Id                       uint64        `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	CPU                      uint32        `protobuf:"varint,2,opt,name=CPU" json:"CPU,omitempty"`
	GPU                      uint32        `protobuf:"varint,3,opt,name=GPU" json:"GPU,omitempty"`
	RAMmb                    uint32        `protobuf:"varint,4,opt,name=RAMmb" json:"RAMmb,omitempty"`
	TimePeriod               uint64        `protobuf:"varint,5,opt,name=TimePeriod" json:"TimePeriod,omitempty"`
	TemporaryStorageNeededGb float32       `protobuf:"fixed32,6,opt,name=TemporaryStorageNeededGb" json:"TemporaryStorageNeededGb,omitempty"`
	Owner                    *Organization `protobuf:"bytes,7,opt,name=Owner" json:"Owner,omitempty"`
}

func (m *ResourceVolume) Reset()                    { *m = ResourceVolume{} }
func (m *ResourceVolume) String() string            { return proto.CompactTextString(m) }
func (*ResourceVolume) ProtoMessage()               {}
func (*ResourceVolume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResourceVolume) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResourceVolume) GetCPU() uint32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *ResourceVolume) GetGPU() uint32 {
	if m != nil {
		return m.GPU
	}
	return 0
}

func (m *ResourceVolume) GetRAMmb() uint32 {
	if m != nil {
		return m.RAMmb
	}
	return 0
}

func (m *ResourceVolume) GetTimePeriod() uint64 {
	if m != nil {
		return m.TimePeriod
	}
	return 0
}

func (m *ResourceVolume) GetTemporaryStorageNeededGb() float32 {
	if m != nil {
		return m.TemporaryStorageNeededGb
	}
	return 0
}

func (m *ResourceVolume) GetOwner() *Organization {
	if m != nil {
		return m.Owner
	}
	return nil
}

type Decision struct {
	// Pairs jobs[idx] -> workers[idx]
	JobIdx    uint64 `protobuf:"varint,1,opt,name=JobIdx" json:"JobIdx,omitempty"`
	WorkerIdx uint64 `protobuf:"varint,2,opt,name=WorkerIdx" json:"WorkerIdx,omitempty"`
}

func (m *Decision) Reset()                    { *m = Decision{} }
func (m *Decision) String() string            { return proto.CompactTextString(m) }
func (*Decision) ProtoMessage()               {}
func (*Decision) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Decision) GetJobIdx() uint64 {
	if m != nil {
		return m.JobIdx
	}
	return 0
}

func (m *Decision) GetWorkerIdx() uint64 {
	if m != nil {
		return m.WorkerIdx
	}
	return 0
}

func init() {
	proto.RegisterType((*Quotum)(nil), "scheduler.Quotum")
	proto.RegisterType((*Organization)(nil), "scheduler.Organization")
	proto.RegisterType((*ResourceVolume)(nil), "scheduler.ResourceVolume")
	proto.RegisterType((*Decision)(nil), "scheduler.Decision")
}

func init() { proto.RegisterFile("schedmessages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x49, 0xda, 0x64, 0xe9, 0xf4, 0x0f, 0x30, 0xa0, 0xc5, 0x42, 0x08, 0xad, 0x72, 0x80,
	0xbd, 0xd0, 0x03, 0xdc, 0x38, 0xb1, 0x2c, 0x52, 0xb6, 0x20, 0x76, 0x53, 0xd3, 0xc2, 0xd9, 0x49,
	0x46, 0x25, 0x50, 0xd7, 0x95, 0x9d, 0x88, 0x3f, 0xdf, 0x97, 0x8f, 0x81, 0x84, 0x6c, 0x27, 0x25,
	0x3d, 0x70, 0xf3, 0xfc, 0xde, 0x9b, 0xd1, 0xcc, 0x4b, 0xe0, 0xbe, 0x29, 0xbe, 0x50, 0x29, 0xc9,
	0x18, 0xb1, 0x21, 0x33, 0xdf, 0x6b, 0x55, 0x2b, 0x1c, 0x39, 0xd8, 0x6c, 0x49, 0x27, 0x7f, 0x02,
	0x88, 0x97, 0x8d, 0xaa, 0x1b, 0x89, 0x09, 0x4c, 0x32, 0xad, 0xbe, 0x52, 0x51, 0x73, 0x51, 0x57,
	0x8a, 0x05, 0x67, 0xc1, 0x79, 0xc8, 0x8f, 0x18, 0x3e, 0x85, 0xe9, 0xe5, 0xbe, 0xb9, 0x52, 0x8d,
	0x36, 0xde, 0x04, 0xd6, 0x74, 0x75, 0x8b, 0x1f, 0x63, 0x7c, 0x04, 0x27, 0x69, 0xee, 0x1d, 0xe3,
	0xd6, 0xd1, 0x01, 0x4c, 0x60, 0xdc, 0x99, 0x2f, 0x72, 0xc3, 0x26, 0xad, 0xde, 0x87, 0x78, 0x0a,
	0x51, 0x9a, 0x5b, 0x75, 0xda, 0xaa, 0xbe, 0xb4, 0xbd, 0x5c, 0xc8, 0x43, 0xef, 0xac, 0xeb, 0xed,
	0x41, 0xbb, 0x63, 0x57, 0xfa, 0x0d, 0xee, 0x74, 0x3b, 0x1e, 0xe1, 0x37, 0x03, 0x08, 0x96, 0xc9,
	0x7b, 0x98, 0xdc, 0xe8, 0x8d, 0xd8, 0x55, 0xbf, 0x2c, 0xdb, 0x21, 0xc2, 0xf0, 0x5a, 0x48, 0x72,
	0xc7, 0x8f, 0xb8, 0x7b, 0xe3, 0x33, 0x88, 0x6c, 0x44, 0x82, 0x85, 0x67, 0xc1, 0xf9, 0xf8, 0xc5,
	0xbd, 0xf9, 0x21, 0xbe, 0xb9, 0x8f, 0x8e, 0x7b, 0x3d, 0xf9, 0x1d, 0xc0, 0x8c, 0x93, 0x51, 0x8d,
	0x2e, 0xe8, 0x93, 0xda, 0x36, 0x92, 0x70, 0x06, 0xe1, 0xa2, 0x74, 0xd3, 0x86, 0x3c, 0x5c, 0x94,
	0x78, 0x17, 0x06, 0x97, 0xd9, 0xda, 0x4d, 0x9a, 0x72, 0xfb, 0xb4, 0x24, 0xcd, 0xd6, 0x6c, 0xe0,
	0x49, 0x9a, 0xad, 0xf1, 0x01, 0x44, 0xfc, 0xe2, 0x83, 0xcc, 0xd9, 0xd0, 0x31, 0x5f, 0xe0, 0x13,
	0x80, 0x55, 0x25, 0x29, 0x23, 0x5d, 0xa9, 0x92, 0x45, 0x6e, 0x62, 0x8f, 0xe0, 0x2b, 0x60, 0x2b,
	0x92, 0x7b, 0xa5, 0x85, 0xfe, 0xf9, 0xb1, 0x56, 0x5a, 0x6c, 0xe8, 0x9a, 0xa8, 0xa4, 0x32, 0xcd,
	0x59, 0xec, 0x3e, 0xe5, 0x7f, 0x75, 0x7c, 0x0e, 0xd1, 0xcd, 0xf7, 0x1d, 0x69, 0x76, 0xe2, 0x2e,
	0x7c, 0xd8, 0xbb, 0xb0, 0x9f, 0x0e, 0xf7, 0xae, 0xe4, 0x35, 0xdc, 0x7e, 0x4b, 0x45, 0x65, 0x6c,
	0x60, 0xa7, 0x10, 0xbf, 0x53, 0xf9, 0xa2, 0xfc, 0xd1, 0x1e, 0xd9, 0x56, 0xf8, 0x18, 0x46, 0x9f,
	0x95, 0xfe, 0x46, 0xda, 0x4a, 0xa1, 0x93, 0xfe, 0x81, 0x3c, 0x76, 0x3f, 0xe2, 0xcb, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd7, 0x61, 0xef, 0x16, 0x9f, 0x02, 0x00, 0x00,
}
