// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scheduler.proto

/*
Package scheduler is a generated protocol buffer package.

It is generated from these files:
	scheduler.proto

It has these top-level messages:
	Quotum
	Organization
	ResourceVolume
	Decision
*/
package scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Quotum struct {
	ProjectRatio float32 `protobuf:"fixed32,1,opt,name=ProjectRatio" json:"ProjectRatio,omitempty"`
	// Types that are valid to be assigned to Q:
	//	*Quotum_CpuTimeRatio
	//	*Quotum_GbRatio
	//	*Quotum_CpuTimeAbs
	//	*Quotum_GbAbs
	Q isQuotum_Q `protobuf_oneof:"Q"`
}

func (m *Quotum) Reset()                    { *m = Quotum{} }
func (m *Quotum) String() string            { return proto.CompactTextString(m) }
func (*Quotum) ProtoMessage()               {}
func (*Quotum) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isQuotum_Q interface {
	isQuotum_Q()
}

type Quotum_CpuTimeRatio struct {
	CpuTimeRatio float32 `protobuf:"fixed32,10,opt,name=CpuTimeRatio,oneof"`
}
type Quotum_GbRatio struct {
	GbRatio float32 `protobuf:"fixed32,11,opt,name=GbRatio,oneof"`
}
type Quotum_CpuTimeAbs struct {
	CpuTimeAbs uint64 `protobuf:"varint,12,opt,name=CpuTimeAbs,oneof"`
}
type Quotum_GbAbs struct {
	GbAbs uint32 `protobuf:"varint,13,opt,name=GbAbs,oneof"`
}

func (*Quotum_CpuTimeRatio) isQuotum_Q() {}
func (*Quotum_GbRatio) isQuotum_Q()      {}
func (*Quotum_CpuTimeAbs) isQuotum_Q()   {}
func (*Quotum_GbAbs) isQuotum_Q()        {}

func (m *Quotum) GetQ() isQuotum_Q {
	if m != nil {
		return m.Q
	}
	return nil
}

func (m *Quotum) GetProjectRatio() float32 {
	if m != nil {
		return m.ProjectRatio
	}
	return 0
}

func (m *Quotum) GetCpuTimeRatio() float32 {
	if x, ok := m.GetQ().(*Quotum_CpuTimeRatio); ok {
		return x.CpuTimeRatio
	}
	return 0
}

func (m *Quotum) GetGbRatio() float32 {
	if x, ok := m.GetQ().(*Quotum_GbRatio); ok {
		return x.GbRatio
	}
	return 0
}

func (m *Quotum) GetCpuTimeAbs() uint64 {
	if x, ok := m.GetQ().(*Quotum_CpuTimeAbs); ok {
		return x.CpuTimeAbs
	}
	return 0
}

func (m *Quotum) GetGbAbs() uint32 {
	if x, ok := m.GetQ().(*Quotum_GbAbs); ok {
		return x.GbAbs
	}
	return 0
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Quotum) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Quotum_OneofMarshaler, _Quotum_OneofUnmarshaler, _Quotum_OneofSizer, []interface{}{
		(*Quotum_CpuTimeRatio)(nil),
		(*Quotum_GbRatio)(nil),
		(*Quotum_CpuTimeAbs)(nil),
		(*Quotum_GbAbs)(nil),
	}
}

func _Quotum_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Quotum)
	// Q
	switch x := m.Q.(type) {
	case *Quotum_CpuTimeRatio:
		b.EncodeVarint(10<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.CpuTimeRatio)))
	case *Quotum_GbRatio:
		b.EncodeVarint(11<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.GbRatio)))
	case *Quotum_CpuTimeAbs:
		b.EncodeVarint(12<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.CpuTimeAbs))
	case *Quotum_GbAbs:
		b.EncodeVarint(13<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.GbAbs))
	case nil:
	default:
		return fmt.Errorf("Quotum.Q has unexpected type %T", x)
	}
	return nil
}

func _Quotum_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Quotum)
	switch tag {
	case 10: // Q.CpuTimeRatio
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_CpuTimeRatio{math.Float32frombits(uint32(x))}
		return true, err
	case 11: // Q.GbRatio
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Q = &Quotum_GbRatio{math.Float32frombits(uint32(x))}
		return true, err
	case 12: // Q.CpuTimeAbs
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Q = &Quotum_CpuTimeAbs{x}
		return true, err
	case 13: // Q.GbAbs
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Q = &Quotum_GbAbs{uint32(x)}
		return true, err
	default:
		return false, nil
	}
}

func _Quotum_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Quotum)
	// Q
	switch x := m.Q.(type) {
	case *Quotum_CpuTimeRatio:
		n += proto.SizeVarint(10<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_GbRatio:
		n += proto.SizeVarint(11<<3 | proto.WireFixed32)
		n += 4
	case *Quotum_CpuTimeAbs:
		n += proto.SizeVarint(12<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.CpuTimeAbs))
	case *Quotum_GbAbs:
		n += proto.SizeVarint(13<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.GbAbs))
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Organization struct {
	Name  string  `protobuf:"bytes,1,opt,name=Name" json:"Name,omitempty"`
	Quota *Quotum `protobuf:"bytes,2,opt,name=Quota" json:"Quota,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetQuota() *Quotum {
	if m != nil {
		return m.Quota
	}
	return nil
}

type ResourceVolume struct {
	Id                       uint64        `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	CPU                      uint32        `protobuf:"varint,2,opt,name=CPU" json:"CPU,omitempty"`
	GPU                      uint32        `protobuf:"varint,3,opt,name=GPU" json:"GPU,omitempty"`
	RAMmb                    uint32        `protobuf:"varint,4,opt,name=RAMmb" json:"RAMmb,omitempty"`
	TimePeriod               uint64        `protobuf:"varint,5,opt,name=TimePeriod" json:"TimePeriod,omitempty"`
	TemporaryStorageNeededGB uint32        `protobuf:"varint,6,opt,name=TemporaryStorageNeededGB" json:"TemporaryStorageNeededGB,omitempty"`
	Owner                    *Organization `protobuf:"bytes,7,opt,name=Owner" json:"Owner,omitempty"`
}

func (m *ResourceVolume) Reset()                    { *m = ResourceVolume{} }
func (m *ResourceVolume) String() string            { return proto.CompactTextString(m) }
func (*ResourceVolume) ProtoMessage()               {}
func (*ResourceVolume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResourceVolume) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResourceVolume) GetCPU() uint32 {
	if m != nil {
		return m.CPU
	}
	return 0
}

func (m *ResourceVolume) GetGPU() uint32 {
	if m != nil {
		return m.GPU
	}
	return 0
}

func (m *ResourceVolume) GetRAMmb() uint32 {
	if m != nil {
		return m.RAMmb
	}
	return 0
}

func (m *ResourceVolume) GetTimePeriod() uint64 {
	if m != nil {
		return m.TimePeriod
	}
	return 0
}

func (m *ResourceVolume) GetTemporaryStorageNeededGB() uint32 {
	if m != nil {
		return m.TemporaryStorageNeededGB
	}
	return 0
}

func (m *ResourceVolume) GetOwner() *Organization {
	if m != nil {
		return m.Owner
	}
	return nil
}

type Decision struct {
	// Pairs jobs[idx] -> workers[idx]
	JobIdx    uint64 `protobuf:"varint,1,opt,name=JobIdx" json:"JobIdx,omitempty"`
	WorkerIdx uint64 `protobuf:"varint,2,opt,name=WorkerIdx" json:"WorkerIdx,omitempty"`
}

func (m *Decision) Reset()                    { *m = Decision{} }
func (m *Decision) String() string            { return proto.CompactTextString(m) }
func (*Decision) ProtoMessage()               {}
func (*Decision) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Decision) GetJobIdx() uint64 {
	if m != nil {
		return m.JobIdx
	}
	return 0
}

func (m *Decision) GetWorkerIdx() uint64 {
	if m != nil {
		return m.WorkerIdx
	}
	return 0
}

func init() {
	proto.RegisterType((*Quotum)(nil), "Quotum")
	proto.RegisterType((*Organization)(nil), "Organization")
	proto.RegisterType((*ResourceVolume)(nil), "ResourceVolume")
	proto.RegisterType((*Decision)(nil), "Decision")
}

func init() { proto.RegisterFile("scheduler.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0xaf, 0xd2, 0x40,
	0x14, 0xc5, 0x99, 0xd2, 0x16, 0xb9, 0xb4, 0x68, 0x26, 0x86, 0x4c, 0x8c, 0x9a, 0xa6, 0xba, 0xe8,
	0x8a, 0x85, 0xee, 0x5c, 0x09, 0x98, 0x14, 0x4c, 0x84, 0x32, 0x82, 0xae, 0xfb, 0xe7, 0x06, 0xab,
	0x94, 0x21, 0xd3, 0x36, 0xea, 0xfb, 0x4e, 0xef, 0x13, 0xbd, 0x2f, 0xf3, 0x32, 0x33, 0x7d, 0x79,
	0xb0, 0x78, 0xbb, 0x7b, 0x7f, 0xe7, 0xf4, 0xa4, 0xe7, 0x66, 0xe0, 0x79, 0x9d, 0xff, 0xc2, 0xa2,
	0x3d, 0xa2, 0x9c, 0x9e, 0xa5, 0x68, 0x44, 0x78, 0x4b, 0xc0, 0xdd, 0xb6, 0xa2, 0x69, 0x2b, 0x1a,
	0x82, 0x97, 0x48, 0xf1, 0x1b, 0xf3, 0x86, 0xa7, 0x4d, 0x29, 0x18, 0x09, 0x48, 0x64, 0xf1, 0x2b,
	0x46, 0xdf, 0x83, 0xb7, 0x38, 0xb7, 0xbb, 0xb2, 0x42, 0xe3, 0x01, 0xe5, 0x59, 0xf6, 0xf8, 0x15,
	0xa5, 0xaf, 0x60, 0x10, 0x67, 0xc6, 0x30, 0xea, 0x0c, 0x0f, 0x80, 0x06, 0x00, 0x9d, 0x77, 0x96,
	0xd5, 0xcc, 0x0b, 0x48, 0x64, 0x2f, 0x7b, 0xfc, 0x82, 0xd1, 0x09, 0x38, 0x71, 0xa6, 0x44, 0x3f,
	0x20, 0x91, 0xbf, 0xec, 0x71, 0xb3, 0xce, 0xfb, 0x40, 0xb6, 0xe1, 0x0c, 0xbc, 0x8d, 0x3c, 0xa4,
	0xa7, 0xf2, 0x46, 0xa5, 0x9d, 0x28, 0x05, 0x7b, 0x9d, 0x56, 0xa8, 0x7f, 0x76, 0xc8, 0xf5, 0x4c,
	0xdf, 0x80, 0xa3, 0x2a, 0xa5, 0xcc, 0x0a, 0x48, 0x34, 0xfa, 0x30, 0x98, 0x9a, 0x82, 0xdc, 0xd0,
	0xf0, 0x8e, 0xc0, 0x98, 0x63, 0x2d, 0x5a, 0x99, 0xe3, 0x0f, 0x71, 0x6c, 0x2b, 0xa4, 0x63, 0xb0,
	0x56, 0x85, 0xce, 0xb0, 0xb9, 0xb5, 0x2a, 0xe8, 0x0b, 0xe8, 0x2f, 0x92, 0xbd, 0xfe, 0xde, 0xe7,
	0x6a, 0x54, 0x24, 0x4e, 0xf6, 0xac, 0x6f, 0x48, 0x9c, 0xec, 0xe9, 0x4b, 0x70, 0xf8, 0xec, 0x5b,
	0x95, 0x31, 0x5b, 0x33, 0xb3, 0xd0, 0xb7, 0x00, 0xaa, 0x47, 0x82, 0xb2, 0x14, 0x05, 0x73, 0x74,
	0xe2, 0x05, 0xa1, 0x9f, 0x80, 0xed, 0xb0, 0x3a, 0x0b, 0x99, 0xca, 0xff, 0xdf, 0x1b, 0x21, 0xd3,
	0x03, 0xae, 0x11, 0x0b, 0x2c, 0xe2, 0x39, 0x73, 0x75, 0xd0, 0x93, 0x3a, 0x7d, 0x07, 0xce, 0xe6,
	0xef, 0x09, 0x25, 0x1b, 0xe8, 0x5e, 0xfe, 0xf4, 0xf2, 0x12, 0xdc, 0x68, 0xe1, 0x67, 0x78, 0xf6,
	0x05, 0xf3, 0xb2, 0x56, 0xc7, 0x99, 0x80, 0xfb, 0x55, 0x64, 0xab, 0xe2, 0x5f, 0x57, 0xad, 0xdb,
	0xe8, 0x6b, 0x18, 0xfe, 0x14, 0xf2, 0x0f, 0x4a, 0x25, 0x59, 0x5a, 0x7a, 0x04, 0x99, 0xab, 0x5f,
	0xc6, 0xc7, 0xfb, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xb6, 0x93, 0x08, 0x2c, 0x02, 0x00, 0x00,
}
